### ISSUE TITLE
Parsing array of objects fails

### ISSUE THREAD

**Issue by svandehoef** [timothee-haudebourg/json-syntax#1]
Parsing an array of objects seems to fail with version 0.6.0.

Here is a minimal example:
```
{
  "key": [
    {
      "key": "value"
    },
    {
      "key": "value"
    }
  ]
}
```
I debugged a bit into the code and it seems to fail at "beginning" the second object because it processes the value generated by the first object instead.

**Comment by timothee-haudebourg** [comment]
Hi, thank for the report. I've just tested it and indeed something goes wrong. I can't believe something like that has gone unnoticed with all the tests. I'm fixing it right now.

**Comment by svandehoef** [comment]
Hi, that was quick. Indeed strange they don't have that case in this json testsuite you're using. Happy to help.
